In [1]:
import numpy as np 
import pandas as pd

import os
for dirname, _, filenames in os.walk('BERT_DATA_DIR'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

BERT_DATA_DIR/valid.csv
BERT_DATA_DIR/train.csv


In [2]:
# import BERT tokenization

!wget --quiet https://raw.githubusercontent.com/tensorflow/models/master/official/nlp/bert/tokenization.py

In [3]:
# If tokenization can't be installed, try:
# !pip install bert-tensorflow 

In [4]:
from bert import tokenization
import tensorflow as tf
import tensorflow_hub as hub
from tensorflow.keras.utils import to_categorical
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [5]:
train_data = pd.read_csv('BERT_DATA_DIR/train.csv', encoding='latin-1')
test_data = pd.read_csv('BERT_DATA_DIR/valid.csv', encoding='latin-1')

In [6]:
train_data.head()

Id                                              Title  \
0  34552656             Java: Repeat Task Every Random Seconds   
1  34553034                  Why are Java Optionals immutable?   
2  34553174  Text Overlay Image with Darkened Opacity React...   
3  34553318         Why ternary operator in swift is so picky?   
4  34553755                 hide/show fab with scale animation   

                                                Body  \
0  <p>I'm already familiar with repeating tasks e...   
1  <p>I'd like to understand why Java 8 Optionals...   
2  <p>I am attempting to overlay a title over an ...   
3  <p>The question is very simple, but I just cou...   
4  <p>I'm using custom floatingactionmenu. I need...   

                                                Tags         CreationDate  \
0                                     <java><repeat>  2016-01-01 00:21:59   
1                                   <java><optional>  2016-01-01 02:03:20   
2  <javascript><image><overlay><react-native><opa...  2016-01-01 02:48:24   
3  <swift><operators><whitespace><ternary-operato...  2016-01-01 03:30:17   
4  <android><material-design><floating-action-but...  2016-01-01 05:21:48   

          Y  
0  LQ_CLOSE  
1        HQ  
2        HQ  
3        HQ  
4        HQ

In [7]:
test_data.head()

Id                                              Title  \
0  34552974  How to get all the child records from differen...   
1  34554721  Retrieve all except some data of the another t...   
2  34555135                                  Pandas: read_html   
3  34555448                           Reader Always gimme NULL   
4  34555752    php rearrange array elements based on condition   

                                                Body  \
0  I am having 4 different tables like \r\nselect...   
1  I have two table m_master and tbl_appointment\...   
2  <p>I'm trying to extract US states from wiki U...   
3  I'm so new to C#, I wanna make an application ...   
4  basically i have this array:\r\n\r\n    array(...   

                                     Tags         CreationDate        Y  
0                       <sql><sql-server>  2016-01-01 01:44:52  LQ_EDIT  
1  <php><mysql><sql><codeigniter><mysqli>  2016-01-01 08:43:50  LQ_EDIT  
2                        <python><pandas>  2016-01-01 09:55:22       HQ  
3                    <sql-server><c#-4.0>  2016-01-01 10:43:45  LQ_EDIT  
4                                   <php>  2016-01-01 11:34:09  LQ_EDIT

### Label Encoding of Labels

In [8]:
label = preprocessing.LabelEncoder()
y = label.fit_transform(train_data['Y'])
y = to_categorical(y)
print(y[:5])

[[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


### Build a BERT layer

In [9]:
# we create a BERT embedding layer by importing the BERT model from hub.KerasLayer
# use the large uncased BERT model
m_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2'
bert_layer = hub.KerasLayer(m_url, trainable=True)

### Encoding the text
we create a BERT vocab_file in the form a numpy array. We then set the text to lowercase and finally we pass our vocab_file and do_lower_case variables to the Tokenizer object.

In [10]:
vocab_file = bert_layer.resolved_object.vocab_file.asset_path.numpy()
do_lower_case = bert_layer.resolved_object.do_lower_case.numpy()
tokenizer = tokenization.FullTokenizer(vocab_file, do_lower_case)

def bert_encode(texts, tokenizer, max_len=512):
    all_tokens = []
    all_masks = []
    all_segments = []
    
    for text in texts:
        text = tokenizer.tokenize(text)
        
        text = text[:max_len-2]
        input_sequence = ["[CLS]"] + text + ["[SEP]"]
        pad_len = max_len-len(input_sequence)
        
        tokens = tokenizer.convert_tokens_to_ids(input_sequence) + [0] * pad_len
        pad_masks = [1] * len(input_sequence) + [0] * pad_len
        segment_ids = [0] * max_len
        
        all_tokens.append(tokens)
        all_masks.append(pad_masks)
        all_segments.append(segment_ids)
        
    return np.array(all_tokens), np.array(all_masks), np.array(all_segments)

AttributeError: module 'tensorflow' has no attribute 'gfile'